name = "example-app"
main = "src/index.ts"
compatibility_date = "2024-11-21"

[[d1_databases]]
binding = "DB"
database_name = "example-db"
# database_id = "<set per-developer>"

[[kv_namespaces]]
binding = "EXAMPLE_CACHE"
# id = "<set per-developer>"

[vars]
ALLOWED_ORIGIN = "http://localhost:3333"
